name: cpk
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        architecture:
          - x64
    name: Cpk ${{ matrix.architecture }} on ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ SECRETS.GH_TOKEN }}
      DISPLAY: :0
    steps:
      - name: Setup Ninja and CMake (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential cmake ninja-build git
      - name: Setup Ninja and CMake (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew update > /dev/null
          brew install \
            cmake ninja
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build CPK
        run: |
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="upload"
          cmake --build build -j16
          cmake --install build
      - name: Run Tests
        working-directory: build
        run: ctest -j8
      - uses: actions/upload-artifact@v3
        with:
          name: cpk-${{ matrix.os }}-${{ matrix.architecture }}
          path: upload
